### ISSUE TITLE
App requires notice of ADA

### ISSUE THREAD

**Issue by BLCRAFT210** [ElemelonWind/cps-counter#1]
This app discriminates against people who have disabilities to the hand or wrist area, by the American Disability Act. I request this repository to have this description in the repository or this repository be removed outright, or else, I am afraid bad things might happen.

**Comment by BLCRAFT210** [comment]
delete this

**Comment by ElemelonWind** [comment]
go away

**Comment by BLCRAFT210** [comment]
I know where u live
